### ISSUE TITLE
It works fine in IISExpress, but failed in Azure and IIS hosting

### ISSUE THREAD

**Issue by xqiu** [idseefeld/FacebookFanpageApp#1]
I got it working perfectly in IISExpress.  But when hosted in Azure app service and local host's IIS, I got 302 redirect from http://localhost//facebookapp/start to http://localhost/(S(gf3a4leuiyjafjltxdjabhae))/facebookapp/start, then by 404.

Are there some part that I missed?

Thanks!

**Comment by idseefeld** [comment]
Sorry, I have no experience with this kind of Azure services.

**Comment by xqiu** [comment]
I found the reason, it's because the web's property i localhost:xxxx/facebookApp, which will not by default run well in IIS hostig as a single site.
